### ISSUE TITLE
Arrow keys sometimes "sticky" in mobile

### ISSUE THREAD

**Issue by wlyoung** [FabMo/FabMo-Engine#396]
On occasion if you press a key in the keypad on a mobile device, the arrow "sticks" and the movement continues after you release the arrow. The arrow stays green and you have to click again to stop the motion.

Unfortunately I can't duplicate on demand but it happened on an ipad this morning in Z. Newest linux and 1.0.3 engine, and running chrome on the IPad

**Comment by ryansturmer** [comment]
ipad only?  Or all mobile?  Seems like you mostly observe it on ipad?

**Comment by SW0rden** [comment]
I have seen this on an Android tablet with FireFox, but not Chrome with the latest image and engine as well.  It is 100% reproducible for me.

**Comment by wlyoung** [comment]
I've also had it happen in the past on android phones with Chrome, both a Galaxy S5 with 1-version-back android and a Motorola Moto g with the latest Android. Will test with Firefox in a little bit.

**Comment by ryansturmer** [comment]
I observed this at least once when the authorization dialog popped up - were you using authorization bill on any of these tools?

**Comment by ryansturmer** [comment]
This is fixed afaik.  We can re-open if not.

**Comment by SW0rden** [comment]
Still see it on an Android tablet in FF only.  Could just be the older Nexus 10 tablet, but it is running version 5.1.1.

**Comment by ryansturmer** [comment]
What version are you running SW0rden?

**Comment by SW0rden** [comment]
Software Version
v1.1.1-1-g2b3fe2c
